const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
const CLEAR_DATA_COUNTER = 'CLEAR_DATA_COUNTER';

export {
  INCREMENT_COUNTER,
  DECREMENT_COUNTER,
  CLEAR_DATA_COUNTER
}

